### PR TITLE
Fix: use correct url scheme in ios

### PR DESCRIPTION
**Pull request by dukhanov**
Fixed:- URL scheme is not applied for the "grabButton" method.
We should specify URL scheme for the Flic app. Once the user has chosen one Flic, it will redirect back to the specified callback URL.

### CODE REVIEW

**Comment by jguix** [comment]
Finally I've been able to compile it for iOS.

I'm getting "Flic exception: Can't find variable: Flic" when deploying the app in an iPad. The iPad has the Flic app installed.

**Comment by dukhanov** [comment]
Could you check, which version of node-xcode have you installed on your mac? 
It should be 0.8.7
type in terminal: 

`npm list xcode`

**Comment by jguix** [comment]
I installed 0.8.7 but I'm getting:

```
$ npm list xcode
/Users/it/Documents/workspace-ionic/Cordova-Flic-Example
└── (empty)

npm ERR! code 1

```

Maybe I need to run npm install in my project directory.

This is my test project:

https://github.com/jguix/Cordova-Flic-Example

**Comment by dukhanov** [comment]
Try to install node-xcode globally:
`sudo npm i -g xcode`

**Comment by dukhanov** [comment]
I will try to install your example project later.

**Pull request merged**
